modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
[[mods]] #mandatory
    modId="carbonage" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Carbon Age" #mandatory
    authors="Cromotus" #optional
    description='''
    This is a mod that adds some simple and some complex things made out of Carbon
    '''

[[dependencies.carbonage]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.carbonage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
